package com.minhe.seckill.dao;

import com.minhe.seckill.pojo.StockOrder;
import com.minhe.seckill.pojo.StockOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StockOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_order
     *
     * @mbg.generated
     */
    long countByExample(StockOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_order
     *
     * @mbg.generated
     */
    int deleteByExample(StockOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_order
     *
     * @mbg.generated
     */
    int insert(StockOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_order
     *
     * @mbg.generated
     */
    int insertSelective(StockOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_order
     *
     * @mbg.generated
     */
    List<StockOrder> selectByExample(StockOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_order
     *
     * @mbg.generated
     */
    StockOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StockOrder record, @Param("example") StockOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StockOrder record, @Param("example") StockOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StockOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StockOrder record);
}