package com.minhe.seckill.api.pojo;

public class StockOrderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_order.user_phone
     *
     * @mbg.generated
     */
    private Long userPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_order.id
     *
     * @return the value of stock_order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_order.id
     *
     * @param id the value for stock_order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_order.user_phone
     *
     * @return the value of stock_order.user_phone
     *
     * @mbg.generated
     */
    public Long getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_order.user_phone
     *
     * @param userPhone the value for stock_order.user_phone
     *
     * @mbg.generated
     */
    public void setUserPhone(Long userPhone) {
        this.userPhone = userPhone;
    }
}